Repository UI-linguistic/phonolab, pull requests merged in 2025-04, with the labels that each got.

#8 Init quiz data upload to backend
  backend/src/data/json/phonic_trio_quiz.json
Labels: enhancement

#11 Prototype Data
  Makefile
  backend/README.md
  backend/instance/phonolab.db
  backend/requirements.txt
  backend/scripts/data_quiz.json
  backend/scripts/seed_quiz.py
  backend/src/api/main.py
  backend/src/models/quiz.py
  backend/src/services/quiz.py
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
Labels: enhancement, FIX

#12 Add vowel data for Learn module (Vowels 101)
  backend/src/data/json/learn_vowels.json
Labels: enhancement

#14 Backend API Sync
  Makefile
  backend/cli/__init__.py
  backend/cli/cli_runner.py
  backend/cli/database.py
  backend/cli/lesson.py
  backend/cli/phoneme.py
  backend/cli/quiz.py
  backend/instance/phonolab.db
  backend/requirements-dev.txt
  backend/requirements.txt
  backend/scripts/clear_all_data.py
  backend/scripts/clear_vowels.py
  backend/scripts/data_quiz.json
  backend/scripts/seed_quiz.py
  backend/scripts/seed_vowels.py
  backend/scripts/seed_word_examples.py
  backend/server.py
  backend/setup.py
  backend/src/api/README.md
  backend/src/api/blueprints.py
  backend/src/api/lesson.py
  backend/src/api/phoneme.py
  backend/src/api/quiz.py
  backend/src/api/user.py
  backend/src/app.py
  backend/src/data/json/learn_vowels.json
  backend/src/data/json/phonic_trio_quiz.json
  backend/src/data/quiz.json
  backend/src/data/vowel.json
  backend/src/models/dataset.py
  backend/src/models/quiz.py
  backend/src/models/user.py
  backend/src/services/lesson.py
  backend/src/services/phoneme.py
  backend/src/services/quiz.py
  backend/src/services/user.py
  backend/src/utils/cli_format.py
  backend/src/utils/format.py
  scripts/detect_env.sh
  scripts/export_path.sh
  scripts/init.sh
  scripts/install.sh
  scripts/sync_backend.sh
Labels: documentation, enhancement, FIX

#16 Lesson card response
  .github/workflows/backend-lint.yml
  .github/workflows/backend-tests.yml
  backend/cli/cli_runner.py
  backend/cli/database.py
  backend/cli/lesson.py
  backend/cli/phoneme.py
  backend/cli/quiz.py
  backend/instance/phonolab.db
  backend/migrations/README
  backend/migrations/alembic.ini
  backend/migrations/env.py
  backend/migrations/script.py.mako
  backend/setup.cfg
  backend/src/api/README.md
  backend/src/api/blueprints.py
  backend/src/api/lesson.py
  backend/src/api/main.py
  backend/src/api/quiz.py
  backend/src/models/lesson.py
  backend/src/models/phoneme.py
  backend/src/services/lesson.py
  backend/src/services/phoneme.py
  backend/src/services/quiz.py
  backend/src/utils/cli_format.py
  backend/src/utils/error_handling.py
  backend/src/utils/format.py
  backend/tests/conftest.py
  backend/tests/test_phoneme.py
  backend/tests/test_quiz.py
  backend/tests/test_quiz_engine.py
Labels: enhancement
